//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "mysql"
    } as const;
    models = {} as const;
    plugins = {};
}
export const schema = new SchemaType();
