//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "mysql"
    } as const;
    models = {
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                username: {
                    name: "username",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                journeys: {
                    name: "journeys",
                    type: "Journey",
                    array: true,
                    relation: { opposite: "createdBy" }
                },
                reservations: {
                    name: "reservations",
                    type: "Reservation",
                    array: true,
                    relation: { opposite: "reservedBy" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.DateTime", args: [{ name: "x", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                username: { type: "String" }
            }
        },
        Journey: {
            name: "Journey",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                startDate: {
                    name: "startDate",
                    type: "DateTime",
                    attributes: [{ name: "@db.DateTime", args: [{ name: "x", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("start_date") }] }] as readonly AttributeApplication[]
                },
                endDate: {
                    name: "endDate",
                    type: "DateTime",
                    attributes: [{ name: "@db.DateTime", args: [{ name: "x", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("end_date") }] }] as readonly AttributeApplication[]
                },
                startCity: {
                    name: "startCity",
                    type: "String",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("start_city") }] }] as readonly AttributeApplication[]
                },
                endCity: {
                    name: "endCity",
                    type: "String",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("end_city") }] }] as readonly AttributeApplication[]
                },
                totalPlaces: {
                    name: "totalPlaces",
                    type: "Int",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("total_places") }] }] as readonly AttributeApplication[]
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_by_id") }] }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "createdBy"
                    ] as readonly string[]
                },
                createdBy: {
                    name: "createdBy",
                    type: "Account",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("createdById")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "journeys", fields: ["createdById"], references: ["id"] }
                },
                reservations: {
                    name: "reservations",
                    type: "Reservation",
                    array: true,
                    relation: { opposite: "journey" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.DateTime", args: [{ name: "x", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Reservation: {
            name: "Reservation",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                journeyId: {
                    name: "journeyId",
                    type: "String",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("journey_id") }] }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "journey"
                    ] as readonly string[]
                },
                reservedById: {
                    name: "reservedById",
                    type: "String",
                    attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("reserved_by_id") }] }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "reservedBy"
                    ] as readonly string[]
                },
                journey: {
                    name: "journey",
                    type: "Journey",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("journeyId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "reservations", fields: ["journeyId"], references: ["id"] }
                },
                reservedBy: {
                    name: "reservedBy",
                    type: "Account",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("reservedById")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "reservations", fields: ["reservedById"], references: ["id"] }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.DateTime", args: [{ name: "x", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("journeyId"), ExpressionUtils.field("reservedById")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                journeyId_reservedById: { journeyId: { type: "String" }, reservedById: { type: "String" } }
            }
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
